name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Bazel
      uses: philwo/bazelisk-action@v1
      with:
        bazelisk-version: latest

    - name: Build the project
      run: |
        bazel build //main:main

    - name: Run the executable
      run: |
        ./bazel-bin/main/main
