name: gitlint CI
on:
  pull_request:

jobs:
  git-lint:
    uses: nicu1989/cicd-workflows/.github/workflows/gitlint.yml@nicu1989_add_gitlint
    with:
      gitlint-file: "./math/.gitlint"
      workflow-version: nicu1989_add_gitlint
