name: gitlint CI
on:
  pull_request:

jobs:
  git-lint:
    uses: nicu1989/cicd-workflows/.github/workflows/gitlint.yml@nicu1989_add_gitlint
    with:
      pr-number: ${{ github.event.pull_request.number }}
      base-branch: ${{ github.event.pull_request.base.ref }}
      gitlint-file: "./math/.gitlint"
      workflow-version: nicu1989_add_gitlint
